from PyEasiest.PyEasiest import ranNum
from PyEasiest.PyEasiest import ranFloat
from PyEasiest.PyEasiest import append
from PyEasiest.PyEasiest import write
from PyEasiest.PyEasiest import osName
from PyEasiest.PyEasiest import cap
from PyEasiest.PyEasiest import package
from PyEasiest.PyEasiest import runCmd
from PyEasiest.PyEasiest import py2dmg
from PyEasiest.PyEasiest import py2exe
from PyEasiest.PyEasiest import read
from PyEasiest.PyEasiest import create
